name: CI/CD MLflow

on:
  push:
    branches: [ main ]

env:
  # Gunakan SQLite file agar metadata tersimpan konsisten selama job berlangsung
  MLFLOW_TRACKING_URI: "sqlite:///mlflow.db"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          pip install mlflow sklearn pandas numpy

      - name: Run mlflow project
        run: |
          # Menjalankan project. MLflow akan otomatis mencatat ke mlflow.db
          mlflow run . --env-manager=local -P csv_path="training/train_pca.csv"

      - name: Get latest MLflow run_id
        run: |
          # Mengambil RUN_ID terbaru dari database SQLite menggunakan python script singkat
          RUN_ID=$(python -c "import mlflow; print(mlflow.search_runs(order_by=['start_time DESC']).iloc[0]['run_id'])")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id detected: $RUN_ID"

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest